## Bernouli Random Variable

In [5]:
import tensorflow as tf
#import tensorflow_probability as tfp
import tensorflow_probability as tfp

In [11]:
prob=0.3
r=tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]], dtype=float32)>

In [8]:
prob=0.7
r=tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.]], dtype=float32)>

In [9]:
y_prev=tf.random.normal((10,1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-1.3825104 ],
       [-0.93090063],
       [-0.15112455],
       [ 0.99205935],
       [-2.087846  ],
       [-0.33548984],
       [ 1.272077  ],
       [ 0.6341548 ],
       [ 0.36994117],
       [ 1.7863836 ]], dtype=float32)>

In [10]:
tf.math.multiply(y_prev,r)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.        ],
       [-0.        ],
       [-0.15112455],
       [ 0.99205935],
       [-2.087846  ],
       [-0.33548984],
       [ 1.272077  ],
       [ 0.6341548 ],
       [ 0.        ],
       [ 1.7863836 ]], dtype=float32)>

# Dropout  layer

In [13]:
from tensorflow import keras

In [14]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [ ]:
model