## Bernouli Random Variable

In [5]:
import tensorflow as tf
#import tensorflow_probability as tfp
import tensorflow_probability as tfp

In [11]:
prob=0.3
r=tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.]], dtype=float32)>

In [8]:
prob=0.7
r=tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.]], dtype=float32)>

In [9]:
y_prev=tf.random.normal((10,1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-1.3825104 ],
       [-0.93090063],
       [-0.15112455],
       [ 0.99205935],
       [-2.087846  ],
       [-0.33548984],
       [ 1.272077  ],
       [ 0.6341548 ],
       [ 0.36994117],
       [ 1.7863836 ]], dtype=float32)>

In [10]:
tf.math.multiply(y_prev,r)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.        ],
       [-0.        ],
       [-0.15112455],
       [ 0.99205935],
       [-2.087846  ],
       [-0.33548984],
       [ 1.272077  ],
       [ 0.6341548 ],
       [ 0.        ],
       [ 1.7863836 ]], dtype=float32)>

# Dropout  layer

In [13]:
from tensorflow import keras

In [14]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1

In [20]:
layer=tf.keras.layers.Dropout(.3, input_shape=(1,))

In [21]:
data=tf.random.normal((10,1))
data

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.17588343],
       [-0.46248433],
       [-1.0595856 ],
       [-1.7844166 ],
       [ 0.7109318 ],
       [-0.69706124],
       [ 0.13242327],
       [-0.23351216],
       [ 0.44561654],
       [-0.1868871 ]], dtype=float32)>

In [22]:
layer(data, training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.25126204],
       [-0.        ],
       [-1.5136937 ],
       [-0.        ],
       [ 0.        ],
       [-0.9958018 ],
       [ 0.        ],
       [-0.3335888 ],
       [ 0.        ],
       [-0.26698157]], dtype=float32)>